name: extra_edge_assignment
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed: ^2.4.1
  go_router: ^14.8.1
  json_serializable: ^6.9.4
  riverpod: ^2.6.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  shimmer: ^3.0.0
  flip_card: ^0.7.0
  animated_background: ^2.0.0
  url_launcher: ^6.3.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  freezed: ^2.4.5
  build_runner: ^2.4.6
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
